[package]
name = "cli"
version = "0.1.0"
authors = ["Rémi Passmoilesel <r.passmoilesel@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
