[package]
name = "memo"
version = "0.1.0"
authors = ["Rémi Passmoilesel <r.passmoilesel@protonmail.com>"]
edition = "2018"
default-run = "memo"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
