
version: '3'

services:

  elasticsearch:
    image: elasticsearch:6.7.2
    container_name: elasticsearch
    restart: always
    environment:
      - cluster.name=elasticsearch-local
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9201:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

